version: '3.7'

services:
  cdn:
    build: .
    env_file: 
     - .env
    restart: always
    ports:
     - "3000:3000"
    networks: 
     - web-net_main

networks: 
  web-net_main:
    external: true
