version: '2.0'

services:
  cdn:
    build: .
    env_file: 
     - .env
    restart: always
    ports:
     - "3000:3000"
    #networks: 
    # - webnet_main

#networks: 
#  webnet_main:
#    external: true
